version: "3.8"

services:
  app:
    # container-name: compose-test
    # image: compose-test
    build:
      target: development
    volumes:
      - ./src:/app/src
    ports:
      - 3000:3000
    # working_dir: /app
    